# Generated by Django 4.1.7 on 2023-03-30 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_hotel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Hotelid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.hotel'),
        ),
    ]
