# Generated by Django 4.1.7 on 2023-03-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_room_hotelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='images',
            field=models.FileField(default='', upload_to='Hotels'),
        ),
    ]
