# Generated by Django 4.1.7 on 2023-03-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_alter_hotel_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='id',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
