# Generated by Django 4.1.7 on 2023-03-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_remove_hotel_id_alter_hotel_email_delete_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, primary_key=True, serialize=False),
        ),
    ]
